name: Design book

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2

      - name: Check for missing pages in SUMMARY.md
        working-directory: ./design
        run: ./verify_summary.sh

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: "latest"

      - name: Build
        working-directory: ./design
        run: mdbook build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        # Only deploy if pushed to the main branch
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./design/book
          # Don't store history of gh-pages branch
          # This ensures that the repository size doesn't grow too much
          force_orphan: true
